import type { Metadata } from "next";
import "./globals.css";
import SurveyContextConstructor from "./Context/SurveyContextConstructor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <>
          <SurveyContextConstructor>{children}</SurveyContextConstructor>
        </>
      </body>
    </html>
  );
}
